### ISSUE TITLE
Login button does nothing

### ISSUE THREAD

**Issue by bepstein111** [jbyerline/PolyPrint#15]
I get the following output on my console after running the recommended command for a one-time instance and loading it in my browser:
```
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 GET /login
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 Returned 200 in 13 ms
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 GET /static/js/main.10164902.js
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 Returned 200 in 5 ms
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 GET /static/css/main.073c9b0a.css
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 Returned 200 in 2 ms
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 GET /PrinterConfig.json
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 Returned 200 in 1 ms
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 GET /Logo_White_192x192.png
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 Returned 200 in 1 ms
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 GET /favicon.ico?v=2.0
 HTTP  8/3/2023 7:42:27 PM 192.168.1.16 Returned 200 in 1 ms
```
Then absolutely nothing happens after that no matter what I do (including logging in with the correct credentials). Refreshing the page causes the same text to come up again as the page reloads each resource. Am I missing something?

Here's my PrinterConfig.json just for reference:

```
{
  "credentials": {
    "username": "admin",
    "password": "12345",
  },
  "printers": [
    {
      "name": "CR-10",
      "URL": "http://192.168.1.22:5000",
      "apiKey": "nope",
    },
    {
      "name": "Ender-3",
      "URL": "http://192.168.1.22:5001",
      "apiKey": "nope",
    }
  ]
}
```

**Comment by jbyerline** [comment]
I have been working on a different branch for awhile. The printerCardOverhaul branch. It contains a lot of changes, including running this as a docker container. I will update the readme and merge it to master and make a new release. Hopefully this will solve your issue.

**Comment by jbyerline** [comment]
I just created a new release. Check it out here:

https://github.com/jbyerline/PolyPrint/releases/tag/v1.0.2

Lmk if you run into any issues, I think the README explains everything you need to know as long as you are familiar with docker.

**Comment by jbyerline** [comment]
@bepstein111 were you able to get this working using the docker container?

**Comment by bepstein111** [comment]
Haven't tried it yet, actually have some free time right now, give me a little bit to try it out...

**Comment by bepstein111** [comment]
Got it up and running! Haven't really done a ton of testing obviously, but she runs!

**Comment by jbyerline** [comment]
Resolved
